### ISSUE TITLE
again: declare: -g: invalid option

### ISSUE THREAD

**Issue by saladpanda** [diego-treitos/linux-smart-enumeration#28]
you gradually reverted your fix for #11 (via commit f14477ca482a33c56157d136b961b0bb552b0ddc and commit aa49197f0fdadd778ddced2d98b3dd524adf050d)

So I'm again getting `declare: -g: invalid option` on older bash versions.

**Comment by diego-treitos** [comment]
Hi, thank you for reporting this... again.

The problem was that it was not properly fixed. Using `eval` was very dangerous depending on what was being assigned, and `export` didn't work properly.

However I think I found a way of doing it that should also work with old bash versions. I am now using `readonly` which seems to declare the variable globally and accepts a variable as variable name.

Please test this version when you can: https://raw.githubusercontent.com/diego-treitos/linux-smart-enumeration/fix%2328/lse.sh

Thanks again for helping improving the tool.

**Comment by diego-treitos** [comment]
I tested the fix in an old bash version (3.something) and this worked. This fix was included in version 1.2
