### ISSUE TITLE
sud000 missing alternate hostname results

### ISSUE THREAD

**Issue by Reelix** [diego-treitos/linux-smart-enumeration#40]
For `sud000` (Can we sudo without a password?), you currently check  
  
`sudo -nS id`  
  
Which only checks if the user can sudo without a password on the current host.  
  
If the user has read-access to their own sudoers file, you can also go
  
`cat "/etc/sudoers.d/$(whoami)"`  
  
Which displays commands that the user can sudo on any host by specifying the `-h` flag on `sudo`

**Comment by diego-treitos** [comment]
@Reelix Thank you taking your time to report this. However I think that either I am not understanding well or maybe you have the wrong idea regarding `sudo` and `sudoers`.

First of all, the `/etc/sudoers.d` is a directory that contains files with rules for sudo.  This is included from the `/etc/sudoers` file with `#include /etc/sudoers.d`.  So there is no such *own user sudoers file* unless some sysadmin set it up that way, but it is not a standard. 

This file shouldn't have read permissions for any user. However I realized that **these files were not checked, so I changed** `sud040` **to include the checks**.

Regarding the `-h` flag, it is my understanding that it does not work by default because it requires a *security policy plugin* that supports remote commands and *sudoers* (the default one) does not. From the `sudo` manual:

```
-h host, --host=host
    Run the command on the specified host if the security policy plugin supports remote commands.
    Note that the sudoers plugin does not currently support running remote commands.  
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

    This may also be used in conjunction with the -l option to list a user's privileges for the remote host.
```

So please let me know if I am not understanding your request and help me understand it better.

**Comment by Reelix** [comment]
> However I realized that these files were not checked, so I changed sud040 to include the checks.

That would cover this case perfectly :) Closing this issue!
